import test from "node:test";
import assert from "node:assert/strict";
import { randomUUID } from "node:crypto";
import { Pool } from "pg";
import { drizzle } from "drizzle-orm/node-postgres";
import { sql } from "drizzle-orm";
import * as schema from "../src/db/schema";
import { recordCommunication } from "../src/lib/integrations/communications";
import type { CommunicationEvent } from "../src/lib/integrations/communication-contract";

test("channel integration: isolation, idempotency, suppression, thread review and WhatsApp authorization (rollback only)", async () => {
  const pool = new Pool({connectionString:process.env.DATABASE_URL});
  const database = drizzle(pool,{schema});
  const rollback = new Error("ROLLBACK_TEST_FIXTURES");
  try {
    await assert.rejects(database.transaction(async tx => {
      const org = Number((await tx.execute(sql`INSERT INTO organizations(name) VALUES('communication rollback test') RETURNING id`)).rows[0].id);
      const project = Number((await tx.execute(sql`INSERT INTO projects(organization_id,name,client_key) VALUES(${org},'rollback test','test-client') RETURNING id`)).rows[0].id);
      const company = Number((await tx.execute(sql`INSERT INTO companies(organization_id,name) VALUES(${org},'rollback test') RETURNING id`)).rows[0].id);
      const lead = Number((await tx.execute(sql`INSERT INTO company_projects(company_id,project_id) VALUES(${company},${project}) RETURNING id`)).rows[0].id);
      const contact = Number((await tx.execute(sql`INSERT INTO contacts(organization_id,company_id,email,whatsapp) VALUES(${org},${company},'recipient@example.invalid','905551112233') RETURNING id`)).rows[0].id);
      const suffix = randomUUID().replaceAll('-','').toUpperCase();
      const account = Number((await tx.execute(sql`INSERT INTO communication_accounts(organization_id,project_id,client_id,channel,provider,address,credential_prefix,enabled,hourly_limit) VALUES(${org},${project},'test-client','email','gmail',${`${suffix}@example.invalid`},${`TEST_${suffix}`},true,2) RETURNING id`)).rows[0].id);
      const event: CommunicationEvent = {direction:'outgoing',external_event_id:'out1',occurred_at:new Date().toISOString(),address:'recipient@example.invalid',lead_id:lead,contact_id:contact,body:'test'};
      const first = await recordCommunication(tx,account,event,org);
      assert.equal(first.status,'configuration_required');
      const second = await recordCommunication(tx,account,event,org);
      assert.equal(second.id,first.id); assert.ok(second.duplicate);
      assert.equal(Number((await tx.execute(sql`SELECT count(*) AS n FROM activities WHERE company_project_id=${lead}`)).rows[0].n),1);
      await assert.rejects(recordCommunication(tx,account,{...event,body:'changed'},org),/event_conflict/);
      await assert.rejects(recordCommunication(tx,account,event,org+1000000),/account_not_found/);
      const other = Number((await tx.execute(sql`INSERT INTO communication_accounts(organization_id,project_id,client_id,channel,provider,address,credential_prefix,enabled) VALUES(${org},${project},'test-client','email','gmail',${`other${suffix}@example.invalid`},${`OTHER_${suffix}`},true) RETURNING id`)).rows[0].id);
      assert.equal((await recordCommunication(tx,other,event,org)).duplicate,false);
      const secondProject = Number((await tx.execute(sql`INSERT INTO projects(organization_id,name,client_key) VALUES(${org},'other client','other-client') RETURNING id`)).rows[0].id);
      const otherClient = Number((await tx.execute(sql`INSERT INTO communication_accounts(organization_id,project_id,client_id,channel,provider,address,credential_prefix,enabled) VALUES(${org},${secondProject},'other-client','email','gmail',${`client${suffix}@example.invalid`},${`CLIENT_${suffix}`},true) RETURNING id`)).rows[0].id);
      assert.equal((await recordCommunication(tx,otherClient,event,org)).status,'review');
      await recordCommunication(tx,account,{...event,external_event_id:'limit2'},org);
      const limited = await recordCommunication(tx,account,{...event,external_event_id:'limit3'},org);
      assert.equal(limited.status,'review');
      assert.equal((await tx.execute(sql`SELECT review_reason FROM communication_messages WHERE id=${Number(limited.id)}`)).rows[0].review_reason,'rate_limit');
      const observed = {...event,external_event_id:'sent-observed',status:'sent' as const,provider_message_id:'provider-1'};
      assert.equal((await recordCommunication(tx,other,observed)).status,'sent');
      const delivery: CommunicationEvent = {direction:'status',external_event_id:'read-1',occurred_at:event.occurred_at,address:event.address,provider_message_id:'provider-1',status:'read'};
      await recordCommunication(tx,other,delivery);
      await recordCommunication(tx,other,{...delivery,external_event_id:'late-delivered',status:'delivered'});
      assert.equal((await tx.execute(sql`SELECT status FROM communication_messages WHERE account_id=${other} AND external_event_id='sent-observed'`)).rows[0].status,'read');
      const nonceEvent: CommunicationEvent = {direction:'incoming',external_event_id:'nonce1',occurred_at:event.occurred_at,address:event.address};
      await recordCommunication(tx,other,nonceEvent,undefined,'nonce-one-123456789');
      await assert.rejects(recordCommunication(tx,other,{...nonceEvent,external_event_id:'nonce2'},undefined,'nonce-one-123456789'),/event_conflict/);
      await recordCommunication(tx,other,{...delivery,external_event_id:'bounce1',status:'bounce'});
      assert.equal((await tx.execute(sql`SELECT reason FROM communication_suppressions WHERE organization_id=${org} AND client_id='test-client' AND address=${event.address}`)).rows[0].reason,'bounce');
      assert.equal((await recordCommunication(tx,other,{...event,external_event_id:'bounce-blocked'},org)).status,'review');
      await tx.execute(sql`INSERT INTO communication_suppressions(organization_id,client_id,channel,address,reason) VALUES(${org},'test-client','email','recipient@example.invalid','do_not_contact') ON CONFLICT(organization_id,client_id,channel,address) DO UPDATE SET reason='do_not_contact'`);
      assert.equal((await recordCommunication(tx,account,{...event,external_event_id:'blocked'},org)).status,'review');
      const incoming: CommunicationEvent = {direction:'incoming',external_event_id:'in1',occurred_at:event.occurred_at,address:'recipient@example.invalid',thread_id:'t1',body:'hello'};
      assert.equal((await recordCommunication(tx,account,incoming)).status,'received');
      assert.equal((await recordCommunication(tx,account,{...incoming,external_event_id:'unknown',address:'nobody@example.invalid'})).status,'review');
      const wa = Number((await tx.execute(sql`INSERT INTO communication_accounts(organization_id,project_id,client_id,channel,provider,address,credential_prefix,enabled) VALUES(${org},${project},'test-client','whatsapp','meta',${suffix},${`WA_${suffix}`},true) RETURNING id`)).rows[0].id);
      assert.equal((await recordCommunication(tx,wa,{...incoming,external_event_id:'wa1',address:'905551112233'})).status,'review');
      await tx.execute(sql`INSERT INTO communication_permissions(account_id,address,allowed) VALUES(${wa},'905551112233',true)`);
      assert.equal((await recordCommunication(tx,wa,{...incoming,external_event_id:'wa2',address:'905551112233'})).status,'received');
      assert.equal((await recordCommunication(tx,wa,{...incoming,external_event_id:'ai',address:'905551112233',body:'/ai leads'})).status,'review');
      const staff = Number((await tx.execute(sql`INSERT INTO users(organization_id,email,password_hash,role) VALUES(${org},${`staff${suffix}@example.invalid`},'unusable-test-hash','viewer') RETURNING id`)).rows[0].id);
      await tx.execute(sql`UPDATE communication_permissions SET user_id=${staff},ai_allowed=true WHERE account_id=${wa} AND address='905551112233'`);
      const ask = {...incoming,external_event_id:'staff-query',address:'905551112233',body:'en yüksek potansiyelli firmalar'};
      assert.equal((await recordCommunication(tx,wa,ask)).status,'assistant_answered');
      const add = {...ask,external_event_id:'staff-add',body:'/firma-ekle {"name":"WhatsApp rollback company"}'};
      const denied = await recordCommunication(tx,wa,add);
      assert.equal((await tx.execute(sql`SELECT action FROM whatsapp_assistant_results WHERE message_id=${Number(denied.id)}`)).rows[0].action,'denied');
      assert.equal(Number((await tx.execute(sql`SELECT count(*) AS n FROM companies WHERE organization_id=${org} AND name='WhatsApp rollback company'`)).rows[0].n),0);
      await tx.execute(sql`UPDATE users SET role='super_admin' WHERE id=${staff}`);
      const adminAdd = {...add,external_event_id:'admin-add'};
      const added = await recordCommunication(tx,wa,adminAdd);
      assert.equal((await tx.execute(sql`SELECT action FROM whatsapp_assistant_results WHERE message_id=${Number(added.id)}`)).rows[0].action,'add_company');
      assert.equal((await recordCommunication(tx,wa,adminAdd)).duplicate,true);
      assert.equal(Number((await tx.execute(sql`SELECT count(*) AS n FROM companies WHERE organization_id=${org} AND name='WhatsApp rollback company'`)).rows[0].n),1);
      const deletion = await recordCommunication(tx,wa,{...ask,external_event_id:'admin-delete',body:'firmayı sil'});
      assert.equal((await tx.execute(sql`SELECT action FROM whatsapp_assistant_results WHERE message_id=${Number(deletion.id)}`)).rows[0].action,'denied');
      throw rollback;
    }),error => error === rollback);
  } finally { await pool.end(); }
});
